# Generated by Django 3.1.7 on 2021-04-17 20:37

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_.user')),
                ('location', models.CharField(blank=True, choices=[('Almaty region', (('almaty', 'Almaty'), ('taldykorgan', 'Taldykorgan'))), ('Akmoly region', (('nur-sultan', 'Nur-Sultan'), ('kokshetau', 'Kokshetau'))), (None, 'Unknown')], max_length=30)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
            bases=('auth_.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, choices=[('Almaty region', (('almaty', 'Almaty'), ('taldykorgan', 'Taldykorgan'))), ('Akmoly region', (('nur-sultan', 'Nur-Sultan'), ('kokshetau', 'Kokshetau'))), (None, 'Unknown')], max_length=100)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startedAt', models.DateField(default=datetime.datetime(2021, 4, 18, 2, 37, 2, 522714))),
                ('subscription_interval', models.SmallIntegerField(choices=[(7, 'every week'), (14, 'every 2 weeks'), (21, 'every 3 weeks'), (30, 'every month'), (models.IntegerField(), 'other')], default=7)),
                ('subscribedProduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('subscriber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_.user')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.shop')),
            ],
            options={
                'verbose_name': 'Владелец магазина',
                'verbose_name_plural': 'Владельцы магазинов',
            },
            bases=('auth_.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ShopFeedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=255, null=True)),
                ('shop_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=255, null=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop'),
        ),
        migrations.CreateModel(
            name='DeliveryGuy',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_.user')),
                ('shopId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.shop')),
            ],
            options={
                'verbose_name': 'Доставщики',
                'verbose_name_plural': 'Доставщик',
            },
            bases=('auth_.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shop'),
        ),
    ]
