# Generated by Django 3.1.7 on 2021-04-17 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='startedAt',
            field=models.DateField(default=datetime.datetime(2021, 4, 17, 19, 40, 39, 76787)),
        ),
    ]
