# Generated by Django 3.1.7 on 2021-04-17 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210418_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='startedAt',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 3, 1, 18, 933721)),
        ),
    ]
