# Generated by Django 3.1.7 on 2021-04-17 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210418_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='startedAt',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 3, 2, 7, 634622)),
        ),
    ]
