# Generated by Django 3.1.7 on 2021-04-23 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210418_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='startedAt',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 1, 20, 11, 768926)),
        ),
    ]
