# Generated by Django 3.1.7 on 2021-04-23 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210424_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.shop'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='startedAt',
            field=models.DateField(default=datetime.datetime(2021, 4, 24, 2, 9, 49, 669679)),
        ),
    ]
