# Generated by Django 3.1.7 on 2021-05-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0004_delete_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverer',
            name='completed_orders_count',
            field=models.IntegerField(default=0),
        ),
    ]
